class AddColumnDrawings < ActiveRecord::Migration[6.0]
  def change
    add_column :drawings, :description, :text
    add_column :drawings, :description_1, :text
    add_column :drawings, :description_2, :text
    add_column :drawings, :description_3, :text
    add_column :drawings, :description_4, :text
    add_column :drawings, :description_5, :text
    add_column :drawings, :image_1, :text
    add_column :drawings, :image_2, :text
    add_column :drawings, :image_3, :text
    add_column :drawings, :image_4, :text
    add_column :drawings, :image_5, :text
    add_column :drawings, :image_6, :text
    add_column :drawings, :image_7, :text
    add_column :drawings, :image_8, :text
    add_column :drawings, :image_9, :text
    add_column :drawings, :image_10, :text
    add_column :drawings, :image_11, :text
    add_column :drawings, :image_12, :text
    add_column :drawings, :image_13, :text
    add_column :drawings, :image_14, :text
    add_column :drawings, :image_15, :text
    add_column :drawings, :image_16, :text
    add_column :drawings, :image_17, :text
    add_column :drawings, :image_18, :text
    add_column :drawings, :image_19, :text
    add_column :drawings, :image_20, :text
    add_column :drawings, :image_21, :text
    add_column :drawings, :image_22, :text
    add_column :drawings, :image_23, :text
    add_column :drawings, :image_24, :text
    add_column :drawings, :image_25, :text
    add_column :drawings, :image_26, :text
    add_column :drawings, :image_27, :text
    add_column :drawings, :image_28, :text
    add_column :drawings, :image_29, :text
    add_column :drawings, :image_30, :text
    add_column :drawings, :image_31, :text
    add_column :drawings, :image_32, :text
    add_column :drawings, :image_33, :text
    add_column :drawings, :image_34, :text
    add_column :drawings, :image_35, :text
    add_column :drawings, :image_36, :text
    add_column :drawings, :image_37, :text
    add_column :drawings, :image_38, :text
    add_column :drawings, :image_39, :text
    add_column :drawings, :image_40, :text
    add_column :drawings, :image_41, :text
    add_column :drawings, :image_42, :text
    add_column :drawings, :image_43, :text
    add_column :drawings, :image_44, :text
    add_column :drawings, :image_45, :text
    add_column :drawings, :image_46, :text
    add_column :drawings, :image_47, :text
    add_column :drawings, :image_48, :text
    add_column :drawings, :image_49, :text
    add_column :drawings, :image_50, :text
    add_column :drawings, :legend_1, :text
    add_column :drawings, :legend_2, :text
    add_column :drawings, :legend_3, :text
    add_column :drawings, :legend_4, :text
    add_column :drawings, :legend_5, :text
    add_column :drawings, :legend_6, :text
    add_column :drawings, :legend_7, :text
    add_column :drawings, :legend_8, :text
    add_column :drawings, :legend_9, :text
    add_column :drawings, :legend_10, :text
    add_column :drawings, :legend_11, :text
    add_column :drawings, :legend_12, :text
    add_column :drawings, :legend_13, :text
    add_column :drawings, :legend_14, :text
    add_column :drawings, :legend_15, :text
    add_column :drawings, :legend_16, :text
    add_column :drawings, :legend_17, :text
    add_column :drawings, :legend_18, :text
    add_column :drawings, :legend_19, :text
    add_column :drawings, :legend_20, :text
    add_column :drawings, :legend_21, :text
    add_column :drawings, :legend_22, :text
    add_column :drawings, :legend_23, :text
    add_column :drawings, :legend_24, :text
    add_column :drawings, :legend_25, :text
    add_column :drawings, :legend_26, :text
    add_column :drawings, :legend_27, :text
    add_column :drawings, :legend_28, :text
    add_column :drawings, :legend_29, :text
    add_column :drawings, :legend_30, :text
    add_column :drawings, :legend_31, :text
    add_column :drawings, :legend_32, :text
    add_column :drawings, :legend_33, :text
    add_column :drawings, :legend_34, :text
    add_column :drawings, :legend_35, :text
    add_column :drawings, :legend_36, :text
    add_column :drawings, :legend_37, :text
    add_column :drawings, :legend_38, :text
    add_column :drawings, :legend_39, :text
    add_column :drawings, :legend_40, :text
    add_column :drawings, :legend_41, :text
    add_column :drawings, :legend_42, :text
    add_column :drawings, :legend_43, :text
    add_column :drawings, :legend_44, :text
    add_column :drawings, :legend_45, :text
    add_column :drawings, :legend_46, :text
    add_column :drawings, :legend_47, :text
    add_column :drawings, :legend_48, :text
    add_column :drawings, :legend_49, :text
    add_column :drawings, :legend_50, :text
  end
end
